version: "3"
services:
    nest:
        container_name: nest
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        env_file: 
            - .env
        ports:
            - ${PORT}:8000
